# Generated by Django 6.0.7 on 2026-08-18 04:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('imported_rice', 'Imported commercial rice'), ('local_rice', 'Local commercial rice'), ('corn', 'Corn products'), ('legumes', 'Legumes'), ('fish', 'Fish products'), ('beef', 'Beef'), ('pork', 'Pork'), ('other_meat', 'Other livestock meat'), ('poultry', 'Poultry'), ('lowland_veg', 'Lowland vegetables'), ('highland_veg', 'Highland vegetables'), ('spices', 'Spices'), ('fruits', 'Fruits'), ('other_basic', 'Other basic commodities'), ('packaged', 'Packaged goods'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('specification', models.CharField(blank=True, help_text='Grade, size or brand, e.g. "Medium (4-6 pcs/kg)".', max_length=160)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('is_tracked', models.BooleanField(default=False, help_text='On your watchlist - these get charted and alerted on.')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'commodities',
                'ordering': ['category', 'name', 'specification'],
                'indexes': [models.Index(fields=['name'], name='idx_commodity_name')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name', 'specification'), name='uniq_commodity_identity')],
            },
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, default='NCR', max_length=40)),
                ('observed_on', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Pesos per unit.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('receipt', 'You paid this'), ('da_daily', 'DA daily price index'), ('dti_srp', 'DTI suggested retail price'), ('spotted', 'Shelf price seen')], default='da_daily', max_length=12)),
                ('source_url', models.URLField(blank=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='grocery.commodity')),
            ],
            options={
                'ordering': ['-observed_on', 'commodity__name'],
                'indexes': [models.Index(fields=['commodity', 'region', '-observed_on'], name='idx_price_series'), models.Index(fields=['-observed_on'], name='idx_price_day')],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'region', 'observed_on', 'source'), name='uniq_commodity_price_per_day')],
            },
        ),
    ]
