# Generated by Django 6.0.7 on 2026-08-18 03:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('default_fuel_type', models.CharField(choices=[('gas_91', 'Gasoline RON 91'), ('gas_95', 'Gasoline RON 95'), ('gas_97', 'Gasoline RON 97'), ('diesel', 'Diesel'), ('diesel_premium', 'Premium diesel')], default='gas_95', max_length=20)),
                ('tank_capacity_l', models.DecimalField(decimal_places=1, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('km_per_liter', models.DecimalField(decimal_places=2, default=10, help_text='Real-world average. The fill-up log refines this over time.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DOEAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.DateField(help_text='Monday of the week the advisory covers.')),
                ('region', models.CharField(db_index=True, max_length=40)),
                ('brand', models.CharField(blank=True, help_text='Blank means prevailing across brands.', max_length=60)),
                ('fuel_type', models.CharField(choices=[('gas_91', 'Gasoline RON 91'), ('gas_95', 'Gasoline RON 95'), ('gas_97', 'Gasoline RON 97'), ('diesel', 'Diesel'), ('diesel_premium', 'Premium diesel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_url', models.URLField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'DOE advisory',
                'verbose_name_plural': 'DOE advisories',
                'ordering': ['-week_of', 'region', 'brand'],
                'indexes': [models.Index(fields=['region', 'fuel_type', '-week_of'], name='idx_advisory_lookup')],
                'constraints': [models.UniqueConstraint(fields=('week_of', 'region', 'brand', 'fuel_type'), name='uniq_advisory_week_region_brand_fuel')],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Canonical brand, e.g. Petron. Normalised on import.', max_length=60)),
                ('brand_raw', models.CharField(blank=True, help_text='Whatever OSM had, kept so a bad normalisation can be traced.', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, db_index=True, help_text='DOE region code, derived from the province. Joins to advisories.', max_length=40)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('is_favorite', models.BooleanField(default=False, help_text='Pinned to the top of comparisons - your usual stops.')),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last import that still found this station in OSM.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_station_latlng'), models.Index(fields=['brand', 'city'], name='idx_station_brand_city')],
                'constraints': [models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='uniq_station_osm_element')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gas_91', 'Gasoline RON 91'), ('gas_95', 'Gasoline RON 95'), ('gas_97', 'Gasoline RON 97'), ('diesel', 'Diesel'), ('diesel_premium', 'Premium diesel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=3, help_text='Pesos per litre.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('fill_up', 'From a fill-up'), ('spotted', 'Price board')], default='spotted', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fuel.station')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='FillUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gas_91', 'Gasoline RON 91'), ('gas_95', 'Gasoline RON 95'), ('gas_97', 'Gasoline RON 97'), ('diesel', 'Diesel'), ('diesel_premium', 'Premium diesel')], max_length=20)),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer_km', models.PositiveIntegerField(blank=True, help_text='Optional. Two readings in a row give real fuel economy.', null=True)),
                ('is_full_tank', models.BooleanField(default=True, help_text='Only full-to-full pairs give a valid economy figure.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('observation', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fill_up', to='fuel.priceobservation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fill_ups', to='fuel.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fill_ups', to='fuel.vehicle')),
            ],
            options={
                'ordering': ['-filled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='priceobservation',
            index=models.Index(fields=['station', 'fuel_type', '-observed_at'], name='idx_obs_station_fuel_time'),
        ),
        migrations.AddIndex(
            model_name='fillup',
            index=models.Index(fields=['-filled_at'], name='idx_fillup_time'),
        ),
        migrations.AddIndex(
            model_name='fillup',
            index=models.Index(fields=['station', '-filled_at'], name='idx_fillup_station'),
        ),
    ]
