# Generated by Django 6.0.7 on 2026-08-18 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doeadvisory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doeadvisory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cheapest price seen in this region, where the source reports one.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doeadvisory',
            name='sample_size',
            field=models.PositiveIntegerField(blank=True, help_text='How many stations the figure was drawn from.', null=True),
        ),
    ]
