# Generated by Django 6.0.7 on 2026-09-23 02:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_doeadvisory_high_doeadvisory_low_and_more'),
        ('places', '0003_geocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSurveyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gas_91', 'Gasoline RON 91'), ('gas_95', 'Gasoline RON 95'), ('gas_97', 'Gasoline RON 97'), ('diesel', 'Diesel'), ('diesel_premium', 'Premium diesel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=3, help_text='Pesos per litre.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('as_of', models.DateField(help_text='The date the survey itself carries.')),
                ('source_name', models.CharField(max_length=80)),
                ('source_url', models.URLField(blank=True)),
                ('station_label', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_survey_prices', to='places.place')),
            ],
            options={
                'ordering': ['place_id', 'fuel_type'],
                'indexes': [models.Index(fields=['fuel_type', 'place'], name='idx_survey_fuel_station')],
                'constraints': [models.UniqueConstraint(fields=('place', 'fuel_type'), name='uniq_survey_station_fuel')],
            },
        ),
    ]
