# Generated by Django 6.0.7 on 2026-08-18 05:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Jollibee, 7-Eleven, Uniqlo… Blank for a store-wide sale.', max_length=60)),
                ('issuer', models.CharField(blank=True, db_index=True, help_text='BPI, BDO, Metrobank… Blank means anyone can use it.', max_length=60)),
                ('card_name', models.CharField(blank=True, help_text='Which card qualifies, e.g. "Gold Rewards". Blank means any card from that issuer.', max_length=120)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('grocery', 'Groceries'), ('dining', 'Dining'), ('apparel', 'Clothing'), ('health', 'Health & pharmacy'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('other', 'Other')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='For a fixed-price deal, e.g. a 99 peso meal.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, help_text='Leave blank only if it genuinely has no end date.', null=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_note', models.CharField(blank=True, help_text='Where you saw it.', max_length=160)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ends_on', '-added_at'],
                'indexes': [models.Index(fields=['category', 'ends_on'], name='idx_promo_lookup')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('grocery', 'Groceries'), ('dining', 'Dining'), ('apparel', 'Clothing'), ('health', 'Health & pharmacy'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('other', 'Other')], db_index=True, max_length=20)),
                ('merchant', models.CharField(blank=True, help_text='Used when the place is not on the map.', max_length=120)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_with', models.CharField(blank=True, help_text='How you paid, e.g. "BPI credit" or "cash". Never card details.', max_length=60)),
                ('reward_earned', models.DecimalField(blank=True, decimal_places=2, help_text='Cashback or points value, if you know it.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('place', models.ForeignKey(blank=True, help_text='Where. Optional - not everything happens somewhere mapped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='places.place')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_wearable', models.BooleanField(default=False, help_text='Track how often this gets worn.')),
                ('wears', models.PositiveIntegerField(default=0)),
                ('retired_on', models.DateField(blank=True, help_text='When you stopped wearing it.', null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spend.purchase')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['-occurred_at'], name='idx_purchase_time'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['category', '-occurred_at'], name='idx_purchase_category'),
        ),
    ]
