# Generated by Django 6.0.7 on 2026-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='source_ref',
            field=models.CharField(blank=True, help_text="The publisher's own id for this promo, so a re-import updates it in place instead of duplicating it.", max_length=160),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['issuer', 'source_ref'], name='idx_promo_source'),
        ),
        migrations.AddConstraint(
            model_name='promo',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref__gt', '')), fields=('issuer', 'source_ref'), name='uniq_promo_source_ref'),
        ),
    ]
