# Generated by Django 6.0.7 on 2026-08-18 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0002_promo_source_ref_promo_idx_promo_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=60)),
                ('model', models.CharField(max_length=120)),
                ('variant', models.CharField(blank=True, help_text='e.g. "Gore-Tex", "Black/Phantom".', max_length=120)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='What you would happily pay. Used to flag a good find.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', 'model', 'variant'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'model', 'variant'), name='uniq_product_identity')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.CharField(blank=True, max_length=40)),
                ('in_stock', models.BooleanField(default=True)),
                ('trust', models.CharField(choices=[('official', "Brand's own store"), ('authorised', 'Authorised stockist'), ('marketplace', 'Marketplace seller'), ('unverified', 'Unverified')], default='unverified', help_text="How far this seller can be trusted. Yours to set - the app only auto-detects the brand's own domains and the known marketplaces.", max_length=12)),
                ('seen_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='spend.product')),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['product', 'price'], name='idx_quote_product')],
            },
        ),
    ]
