# Generated by Django 6.0.7 on 2026-08-18 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('ran_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('rows', models.PositiveIntegerField(default=0, help_text='Rows written or updated by this run.')),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['source', '-ran_at'], name='idx_sourcerun_latest')],
            },
        ),
    ]
