# Generated by Django 6.0.7 on 2026-08-18 05:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What you call it.', max_length=80)),
                ('issuer', models.CharField(blank=True, help_text='BPI, BDO, Metrobank…', max_length=80)),
                ('network', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('other', 'Other')], default='visa', max_length=20)),
                ('last_four', models.CharField(blank=True, help_text='Last four digits only - never the full number.', max_length=4)),
                ('statement_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month the statement cuts.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('due_days_after_statement', models.PositiveSmallIntegerField(default=20, help_text='Days from statement date to payment due date.')),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cashback', 'Cashback'), ('rebate', 'Rebate'), ('points', 'Points'), ('miles', 'Miles'), ('discount', 'Discount')], default='cashback', max_length=12)),
                ('category', models.CharField(blank=True, choices=[('fuel', 'Fuel'), ('grocery', 'Groceries'), ('dining', 'Dining'), ('apparel', 'Clothing'), ('health', 'Health & pharmacy'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('other', 'Other')], help_text='Leave blank to earn on everything.', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Only at this brand, e.g. Shell. Blank means any.', max_length=60)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent back, or points per 100 pesos for a points card.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_per_point', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='What one point is worth in pesos, so cards can be compared.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Most this rule can earn in a month, in pesos. Blank = uncapped.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Single-receipt minimum for this rule to apply.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Blank means ongoing.', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cards.card')),
            ],
            options={
                'ordering': ['-rate', 'card__name'],
                'indexes': [models.Index(fields=['category', 'brand'], name='idx_reward_lookup')],
            },
        ),
    ]
