# Generated by Django 6.0.7 on 2026-08-18 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fuel', 'Fuel station'), ('market', 'Public market'), ('supermarket', 'Supermarket'), ('convenience', 'Convenience store'), ('fast_food', 'Fast food'), ('restaurant', 'Restaurant'), ('mall', 'Mall or department store'), ('pharmacy', 'Pharmacy')], db_index=True, max_length=20)),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Canonical brand, e.g. Petron or Puregold. Normalised on import.', max_length=60)),
                ('brand_raw', models.CharField(blank=True, help_text='Whatever OSM had, kept so a bad normalisation can be traced.', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, db_index=True, help_text='DOE/DA region code, derived from the area imported.', max_length=40)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('is_favorite', models.BooleanField(default=False, help_text='Pinned to the top of comparisons - the ones you actually use.')),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last import that still found this place in OSM.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['kind', 'latitude', 'longitude'], name='idx_place_kind_latlng'), models.Index(fields=['brand', 'city'], name='idx_place_brand_city')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'osm_type', 'osm_id'), name='uniq_place_osm_element')],
            },
        ),
    ]
