# Generated by Django 6.0.7 on 2026-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='kind',
            field=models.CharField(choices=[('fuel', 'Fuel station'), ('market', 'Public market'), ('supermarket', 'Supermarket'), ('convenience', 'Convenience store'), ('fast_food', 'Fast food'), ('restaurant', 'Restaurant'), ('mall', 'Mall or department store'), ('clothes', 'Clothing shop'), ('pharmacy', 'Pharmacy')], db_index=True, max_length=20),
        ),
    ]
