# Generated by Django 6.0.7 on 2026-08-18 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('region', models.CharField(max_length=40)),
                ('region_name', models.CharField(blank=True, max_length=80)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('looked_up_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'geocode cache entry',
                'verbose_name_plural': 'geocode cache',
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude'), name='uniq_geocache_point')],
            },
        ),
    ]
